version: '3.9'
services:
  terraform:
    image: 'hashicorp/terraform:0.11.15'
    volumes:
      - ./src:/app
      - ~/.ssh:/root/.ssh
      - ~/.aws:/root/.aws
    working_dir: '/app'
    entrypoint: ""
